### ISSUE TITLE
Gears PHP 7 Compatible?

### ISSUE THREAD

**Issue by tammy1999** [wecodemore/WordPress-Gear#141]
Is Gears PHP 7 compatible??  I tried to run it through a PHP 7 Plugin Compatible software but it keeps coming back as too large to review.

**Comment by thefuxia** [comment]
WP Gear is not written in PHP. It is written in MarkDown, hence the ending `.md`. You need a parser compatible to [CommonMark](http://commonmark.org/). And then you'll find that the files are compatible with the latest and greatest version, [0.26](http://spec.commonmark.org/0.26/).

**Comment by tammy1999** [comment]
Thank you toscho for your response.  Since I am not a coder and just wanting to transfer my site to a PHP 7 server, will Gears be compatible and not cause errors when I do that.  TYIA

**Comment by GaryJones** [comment]
@tammy1999 I think there's some confusion here.

This repo is not a plugin. It is a directory of useful WordPress developer tools (which may include plugins), which you can view at http://wpgear.org/. There is nothing to install on your WordPress site, so the choice of PHP version you have (kudos for PHP 7 btw) has absolutely no effect.

You may be thinking of https://github.com/10up/WP-Gears or a completely different plugin of a similar name. If you want to post a screenshot, or a link to the plugin you already have, we might be able to help you determine the correct author to ask your question to.

In any event, I'll close this, as it's an invalid question regarding the content of this repo.

**Comment by tammy1999** [comment]
Yes.  I have posted the wrong and I apologize.

**Comment by franz-josef-kaiser** [comment]
@tammy1999 No worries. Happens to the best.
